### PR TITLE
Turkish Translation

### PR DESCRIPTION
**Pull request by fmimza**
Hi I just added tr local files translations. I can help if there is any problem. Good luck.

### CODE REVIEW

**Comment by Bahanix** [comment]
Hello, thank you very much for this translation!

**Comment by dbucci24** [comment]
do you need spanish translations?

**Comment by Bahanix** [comment]
@dbucci24 all PRs are welcome

**Comment by dbucci24** [comment]
@Bahanix  thanks .. what files can be translated? all of them?

**Comment by Bahanix** [comment]
All language files are here: https://github.com/Bahanix/RubyBB/tree/master/config/locales

At the moment only devise.views is already translated to spanish.

**Comment by dbucci24** [comment]
thank you.. tomorrow i will start the translation.

**Comment by dbucci24** [comment]
@Bahanix hey, can you check my translation to spanish? I made it 3 days ago, thanks :)

**Pull request merged**
